package org.example.inventory_manager_beta1.Entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.example.inventory_manager_beta1.DataEnums.AccessLevel;
import java.util.List;

/**
 * A robust Entity class for modeling an Employee within the inventory management system
 */
@Entity
@Getter
@Setter
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "Employees")
@ToString //Spring auto-generated toString method
public class Employee {
    /**
     * An Integer variable automatically generated by Spring at object
     * creation represents the Employee's identification number
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "employee_id")
    private Integer employeeId;
    /**
     * A Unique String variable representing the Employee's
     * Social Security Number. This variable is excluded from
     * Springs ToString method
     */
    @Column(name = "ssn", unique = true)
    @ToString.Exclude //Excluded from toString()
    private String ssn;
    /**
     * A String variable representing the Employee's first name
     */
    @Column(name = "first_name")
    private String firstName;
    /**
     * A String variable representing the Employee's last name
     */
    @Column(name = "last_name")
    private String lastName;
    /**
     * A Unique String variable representing the Employee's username
     */
    @Column(name = "user_name", unique = true)
    private String userName;
    /**
     * A AccessLevel Enumerated Constant representing the Employee's
     * system access level. This variable is interpreted as a String
     * literal in the Employee table in H2 or MySQL
     */
    @Column(name = "access_level")
    @Enumerated(EnumType.STRING)
    private AccessLevel accessLevel;
    /**
     * A Unique String variable representing the Employee's email address
     */
    @Column(name = "email", unique = true)
    private String email;
    /**
     * A Unique String variable representing the Employee's phone number.
     */
    @Column(name = "phone_number", unique = true)
    private String phoneNumber;

    /**
     * A List variable representing the Shifts the Employee has been assigned
     */
    @OneToMany(mappedBy = "employee", fetch = FetchType.LAZY)
    @JsonIgnore
    @ToString.Exclude
    private List<Shift> shifts;
    /**
     * A String variable representing the Employee's password (post hashing)
     */
    @Column(name = "password")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) //Updated so password is stored, but can never be accessed
    @ToString.Exclude
    private String password;

    /**
     * INIT: The No Args constructor required by SpringBoot
     */
    public Employee() {}

    /**
     * INIT: The Minimal Args constructor for creating an Employee
     * @param ssn
     *  The Social Security Number of the Employee
     * @param firstName
     *  The first name of the Employee
     * @param userName
     *  The username of the Employee
     */
    public Employee(String ssn, String firstName, String userName) {
        this.ssn = ssn;
        this.firstName = firstName;
        this.userName = userName;
    }

    /**
     * INIT: The All Args constructor for creating an Employee
     * @param ssn
     *  The Social Security Number of the Employee
     * @param firstName
     *  The first name of the Employee
     * @param lastName
     *  The last name of the Employee
     * @param userName
     *  The username of the Employee
     * @param email
     *  The email address of the Employee
     * @param phoneNumber
     *  The phone number of the Employee
     */
    public Employee(String ssn, String firstName, String lastName, String userName, String email, String phoneNumber) {
        this.ssn = ssn;
        this.firstName = firstName;
        this.lastName = lastName;
        this.userName = userName;
        this.email = email;
        this.phoneNumber = phoneNumber;
    }
}
