package org.example.inventory_manager_beta1.Entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * A robust Entity class representing a change made to an Inventory being managed
 */
@Entity
@Getter
@Setter
@Table(name = "InventoryChanges")
@ToString
public class InventoryChange {
    /**
     * An Integer variable automatically generated by SpringBoot at object
     * creation representing the change's identification number
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "change_id")
    private Integer changeId;
    /**
     * An Integer variable representing the SKU number of an Item
     */
    @Column(name = "sku_number")
    private Integer skuNumber;
    /**
     * An Integer variable representing the amount of an Item that exists
     * in the Inventory
     */
    @Column(name = "amount_of_item")
    private Integer amountOfItem;
    /**
     * An Integer variable representing the ID of the Employee that made the
     * Inventory change
     */
    @Column(name = "employee_id")
    private Integer employeeId;

    /**
     * INIT: The No Args constructor required by SpringBoot
     */
    public InventoryChange() {}

    /**
     * INIT: The All Args constructor for creating an Inventory Change
     * @param skuNumber
     *  The SKU number of the Item being modified
     * @param amountOfItem
     *  The new amount of Item that exists in the Inventory
     * @param employeeId
     *  The ID of the Employee that made the change
     */
    public InventoryChange(Integer skuNumber, Integer amountOfItem, Integer employeeId){
        this.skuNumber = skuNumber;
        this.amountOfItem = amountOfItem;
        this.employeeId = employeeId;
    }
}
