package org.example.inventory_manager_beta1.Entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * A robust Entity class representing the actual Inventory being managed
 */
@Entity
@Getter
@Setter
@Table(name = "Inventory")
@ToString
public class Inventory {
    /**
     * An Integer variable automatically generated by spring at object
     * creation representing the identification number of the item
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sku_number")
    private Integer skuNumber;
    /**
     * A String variable representing an Item's name in the Inventory
     */
    @Column(name = "item_name")
    private String itemName;
    /**
     * A String variable representing a description of an Item in the Inventory
     */
    @Column(name = "item_description")
    private String itemDescription;
    /**
     * An Integer variable representing the number of Item's in the Inventory currently
     */
    @Column(name = "amount_of_item")
    private Integer amountOfItem;

    /**
     * INIT: The No Args constructor required by SpringBoot
     */
    public Inventory() {}

    /**
     * INIT: The Minimal Args constructor for creating an Inventory
     * @param itemName
     *  The name of the Item being added
     * @param amountOfItem
     *  The amount of the Item being added
     */
    public Inventory(String itemName, Integer amountOfItem) {
        this.itemName = itemName;
        this.amountOfItem = amountOfItem;
    }

    /**
     * INIT: The All Args constructor for creating an Inventory
     * @param itemName
     *  The name of the Item being added
     * @param itemDescription
     *  A description about the Item
     * @param amountOfItem
     *  The amount of Item being added
     */
    public Inventory(String itemName, String itemDescription, Integer amountOfItem) {
        this.itemName = itemName;
        this.itemDescription = itemDescription;
        this.amountOfItem = amountOfItem;
    }
}
