package org.example.inventory_manager_beta1.Entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.example.inventory_manager_beta1.DataEnums.StorageType;
import java.time.LocalDate;

/**
 * A robust Entity class representing an Item that exists in an Inventory
 */
@Entity
@Getter
@Setter
@Table(name = "Items")
@ToString
public class Item {
    /**
     * An Integer variable automatically generated by SpringBoot at object
     * creation representing the Item's identification number
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sku_id")
    private Integer skuId;
    /**
     * A String variable representing the Item's name
     */
    @Column(name = "item_name")
    private String itemName;
    /**
     * A String variable representing the Item's description
     */
    @Column(name = "description")
    private String description;
    /**
     * A ShippingCompany variable mapping an Item to a shipping company,
     * representing which company makes the Item
     */
    @ManyToOne
    @JoinColumn(name = "company_id")
    @JsonIgnoreProperties("items")
    private ShippingCompany shippingCompany;
    /**
     * A Shipment variable mapping the Item to a shipmentId, representing
     * which shipment the Item came in on
     */
    @ManyToOne
    @JoinColumn(name = "shipment_id")
    @JsonIgnoreProperties("items")
    private Shipment shipment;
    /**
     * A String variable representing the Item's storage location
     */
    @Column(name = "storage_location")
    private String storageLocation;
    /**
     * An Integer variable representing how much of the Item is in storage
     */
    @Column(name = "quantity")
    private Integer quantity;
    /**
     * A Double variable representing how much the Item weighs per unit
     */
    @Column(name = "weight_lbs")
    private Double weight;
    /**
     * A StorageType Enumerated Constant representing how the Item is stored.
     * This variable is represented as a String literal in H2 and MySQL
     */
    @Column(name = "storage_type")
    @Enumerated(EnumType.STRING)
    private StorageType storageType;
    /**
     * A LocalDate variable representing the date the Item arrived
     */
    @Column(name = "arrival_date")
    private LocalDate arrivalDate;

    /**
     * INIT: The No Args constructor required by SpringBoot
     */
    public Item() {
    }

    /**
     * INIT: The Minimal Args constructor for creating an Item
     * @param itemName
     *  The name of the Item
     * @param storageLocation
     *  The storage location of the Item
     * @param quantity
     *  The amount of the Item
     * @param storageType
     *  The storage type of the Item
     */
    public Item(String itemName, String storageLocation, Integer quantity, StorageType storageType) {
        this.itemName = itemName;
        this.storageLocation = storageLocation;
        this.quantity = quantity;
        this.storageType = storageType;
    }

    /**
     * INIT: The All Args constructor for creating an Item
     * @param itemName
     *  The name of the Item
     * @param description
     *  The description of the Item
     * @param storageLocation
     *  The storage location of the Item
     * @param quantity
     *  The amount of the Item
     * @param weight
     *  The weight per unit of the Item
     * @param storageType
     *  The storage type of the Item
     * @param arrivalDate
     *  The arrival date of the Item
     */
    public Item(String itemName, String description, String storageLocation, Integer quantity, Double weight, StorageType storageType, LocalDate arrivalDate) {
        this.itemName = itemName;
        this.description = description;
        this.storageLocation = storageLocation;
        this.quantity = quantity;
        this.weight = weight;
        this.storageType = storageType;
        this.arrivalDate = arrivalDate;
    }
}
