package org.example.inventory_manager_beta1.Entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * A robust Entity class representing a Shift that has been assigned to an Employee
 */
@Entity
@Getter
@Setter
@Table(name = "shifts")
@ToString
public class Shift {
    /**
     * An Integer variable automatically generated by SpringBoot at object
     * creation representing the Shift's identification number
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    /**
     * An Employee variable representing the Employee the Shift
     * has been assigned to
     */
    @ManyToOne
    @JoinColumn(name = "employee_id")
    @JsonIgnoreProperties("shifts")
    private Employee employee;
    /**
     * A LocalTime variable representing the Shift's start time
     */
    @Column(name = "start_time")
    private LocalTime startTime;
    /**
     * A LocalTime variable representing the Shift's end time
     */
    @Column(name = "end_time")
    private LocalTime endTime;
    /**
     * A Double variable representing the Shift's duration
     */
    @Column(name = "duration")
    private Double duration;
    /**
     * A LocalDate variable representing the Shift's date
     */
    @Column(name = "shift_date")
    private LocalDate shiftDate;

    /**
     * INIT: No Args constructor required by SpringBoot
     */
    public Shift() {}

    /**
     * INIT: The All Args constructor for creating a Shift
     * @param startTime
     *  The start time of the shift
     * @param endTime
     *  The end time of the shift
     * @param shiftDate
     *  The date of the shift
     */
    public Shift (LocalTime startTime, LocalTime endTime, LocalDate shiftDate) {
        this.startTime = startTime;
        this.endTime = endTime;
        this.shiftDate = shiftDate;
        calculateDuration();
    }

    /**
     * A logic method to calculate the duration of the shift based off
     * the given start time and end time
     */
    public void calculateDuration() {
        if (startTime != null && endTime != null) {
            this.duration = (double) Duration.between(startTime, endTime).toMinutes() / 60;
        }
    }
}
