package org.example.inventory_manager_beta1.Entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * A robust Entity class representing a ShippingCompany responsible for making certain Items
 */
@Entity
@Getter
@Setter
@Table(name = "Shipping_Companies")
@ToString
public class ShippingCompany {
    /**
     * An Integer variable automatically generated by SpringBoot at object
     * creation representing the Shipping Company's identification number
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "company_id")
    private Integer shippingCompanyId;
    /**
     * A String variable representing the Shipping Company's name
     */
    @Column(name = "company_name")
    private String shippingCompanyName;
    /**
     * A String variable representing the Shipping Company's email address
     */
    @Column(name = "company_email")
    private String shippingCompanyEmail;
    /**
     * A String variable representing the Shipping Company's phone number
     */
    @Column(name = "company_phone")
    private String shippingCompanyPhone;
    
    /**
     * INIT: The No Args constructor required by SpringBoot
     */
    public ShippingCompany() {}

    /**
     * INIT: The All Args constructor for creating a Shipping Company
     * @param companyName
     *  The name of the Shipping Company
     * @param companyEmail
     *  The email address of the Shipping Company
     * @param companyPhone
     *  The phone number of the Shipping Company
     */
    public ShippingCompany(String companyName, String companyEmail, String companyPhone) {
        this.shippingCompanyName = companyName;
        this.shippingCompanyEmail = companyEmail;
        this.shippingCompanyPhone = companyPhone;
    }
}
