package org.example.inventory_manager_beta1.Entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * A robust Entity class representing a Shipment of Items being sent to an
 * inventory management agency
 */
@Entity
@Getter
@Setter
@Table(name = "Shipments")
@ToString(exclude = {"items", "drivers", "shippingCompanies"})
public class Shipment {
    /**
     * An Integer variable automatically generated by SpringBoot at object
     * creation representing the Shipment's identification number
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "shipment_id")
    private Integer shipmentId;
    /**
     * A LocalDate variable representing the date the Shipment is going to arrive
     */
    @Column(name = "delivery_date")
    private LocalDate arrivalDate;
    /**
     * A Boolean variable representing a flag signaling if the Shipment has arrived
     */
    @Column(name = "arrived")
    private Boolean arrived;
    /**
     * A Boolean variable representing a flag signaling if the Shipment has been offloaded
     * and it's Items have been put into storage
     */
    @Column(name = "offloaded")
    private Boolean offloaded;
    /**
     * A List variable mapping the Shipment to the Item's table showing which items were
     * included in the Shipment
     */
    @OneToMany(mappedBy = "shipment", cascade = {CascadeType.ALL})
    @JsonIgnore
    private List<Item> items;
    /**
     * A List variable mapping the Shipment to the ShippingCompany table, representing
     * which shipping companies are responsible for delivering the Shipment
     */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "shipment_companies",
            joinColumns = @JoinColumn(name = "shipment_id"),
            inverseJoinColumns = @JoinColumn(name = "company_id")
    )
    @JsonIgnore
    private List<ShippingCompany> shippingCompanies;
    /**
     * A List variable mapping the Shipment to the Driver table, representing
     * which drivers are assigned to transport the Shipment
     */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "shipment_drivers",
            joinColumns = @JoinColumn(name = "shipment_id"),
            inverseJoinColumns = @JoinColumn(name = "driver_id")
    )
    @JsonIgnore
    private List<Driver> drivers;
    /**
     * An Admin variable representing the administrator who created and
     * requested the Shipment
     */
    @ManyToOne
    @JoinColumn(name = "created_by")
    @JsonIgnore
    private Admin creationAdmin;

    /**
     * INIT: The No Args constructor required by SpringBoot
     */
    public Shipment() {}

    /**
     * INIT: The Minimal Args constructor for creating a Shipment
     * @param arrivalDate
     *  The date the Shipment will arrive
     */
    public Shipment(LocalDate arrivalDate) {
        this.arrivalDate = arrivalDate;
        this.arrived = false;
        this.offloaded = false;
    }

    /**
     * INIT: The All Args constructor for creating a Shipment
     * @param arrivalDate
     *  The date the Shipment will arrive
     * @param creationAdmin
     *  The Admin who requested the Shipment
     * @param items
     *  The List of Items the Shipment is carrying
     */
    public Shipment(LocalDate arrivalDate, Admin creationAdmin, List<Item> items) {
        this.arrivalDate = arrivalDate;
        this.creationAdmin = creationAdmin;
        this.items = items;
        this.arrived = false;
        offloaded = false;
        this.drivers = new ArrayList<>();
        this.shippingCompanies = new ArrayList<>();
    }
}
